env:
  global:
  - PGPORT=5433
services:
  - postgresql
addons:
  postgresql: "10.1"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
  - 2.5.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
